const questions = [
  { id: 1, question: 'What is your Characters name?', type: 'text' },
  {
    id: 2,
    question: 'What Race would you like to play?',
    type: 'select',
    options: [
      'Badgurix',
      'Augtens',
      'Asura',
      'Archs',
      'Antaleer',
      'Ikaw',
      'Gira',
      'Isegun',
      'Glowhraun',
      'Telecliss',
      'Hwamps',
      'Giants',
      'Taurava',
      'Warve',
      'Selvan',
      'Namors',
      'Elvitch',
      'Taotum',
      'Vulturan',
      'Ryderz',
      'Lightling',
      'Musculus',
      'Gemborne',
      'Elves',
      'Larve',
      'Ruetree',
      'Eltic',
      'Viporian',
      'Crimrik',
      'Mirrormen',
      'Froll',
      'Peaton',
      'Roostins',
      'Dragonaire',
      'Dwarves',
      'Humans',
      'Contruct',
      'Panthari',
      'Redhorn',
      'Minotaur',
      'Laotu',
      'Turtan',
      'Djinni',
      'Foxum',
      'Havgin',
      'Ramiel',
      'Centorc',
      'Tunkles',
      'Denbark',
      'Owlec',
      'Jedanako',
      'Torro',
      'Gorak',
      'Caneis',
      'Spelorian',
      'Troll',
      'Q',
      'Soulless',
      'Demon',
      'Zarut',
      'Otorc',
      'Brinx',
      'Toric',
      'Duogoblin',
      'Melanni',
      'Gonjic',
      'Jaddehb',
      'Polkans',
      'Zadnaut',
      'Skorc',
      'Delvian',
      'Tib',
      'Orc',
      'Jackal',
      'Drowland',
      'Manticlus',
      'Octubian',
      'Dawsp',
      'Boon',
      'Trinon',
      'Shifter',
      'Thyst',
      'Wereman',
      'Ivotien',
      'Mannenite',
      'Dragon',
      'Oakrels',
      'Felynx',
      'Treeton',
      'Goblin',
      'Blood Elf',
      'Cuth',
      'Magelv',
      'Bisanu',
      'Potec',
      'Banda',
      'Cabat',
      'Cossakus',
    ],
  },
  { id: 3, question: 'What is your Characters age?', type: 'number' },
  {
    id: 4,
    question: 'What is your Characters Origin?',
    type: 'select',
    options: [
      'Divine',
      'Eye',
      'Mind',
      'Body',
      'Husk*',
      'Insane*',
    ],
  },
  {
    id: 5,
    question: 'What is your Focus?',
    type: 'select',
    options: [
      'Light',
      'Teleportation',
      'Fire',
      'Air',
      'Mind',
      'Body',
      'Lightning',
      'Health',
      'Water',
    ],
  },
  { id: 6, question: 'What is your Characters goal?', type: 'text' },
  { id: 7, question: 'What is your Characters flaw?', type: 'text' },
  { id: 8, question: 'What is your Characters strength?', type: 'text' },
];

export default questions;