const raceData = {
    "Badgurix": {
      raceDescription: "A badger like race of strong warriors",
      racialBonus: "Strength +1",
      racialAbility: "Shield Proficiency",
      racialNegative: "Intelligence =1",
      hpBonus: "+10",
      startingJinx: "30",
        startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D8",
      picture: "Badgurix",
    },
    "Telecliss": {
      raceDescription: "A plant like race of humanoids known for their kinship with nature ",
      racialBonus: "Reflex +5",
      racialAbility: "Telepathy",
      racialNegative: "Cannot Speak any spoken language",
      hpBonus: "+9",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D6",
        defenseProwess: "D10",
        picture: "Telecliss",
    },
    "Augtens": {
        raceDescription: "A race of aquatic humanoids known for the symbiotic relationship with intelliegent squids",
        racialBonus: "Intelligence +2",
        racialAbility: "Water Breathing",
        racialNegative: "Fortitude -2",
        hpBonus: "+7",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D10",
        defenseProwess: "D6",
        picture: "Augtens",
    },
    "Cabat": {
        raceDescription: "A race of Gremlin batlike hybrids known for their cunning and trickery",
        racialBonus: "Dexterity +2",
        racialAbility: "Flight",
        racialNegative: "Strength -2",
        hpBonus: "+5",
        startingJinx: "20",
        startingLevel: "1",
        attackProwess: "D8",
        defenseProwess: "D8",
        picture: "Cabat",
    },
    "Asura": {
      raceDescription: "A race of lizard-skinned humanoids for their ability to survive desert like conditions and some even fly with their insect like wings",
      racialBonus: "Intelligence +1",
      racialAbility: "Flight - Focus Ablility",
      racialNegative: "Fortitude -2",
      hpBonus: "+8",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D8",
        defenseProwess: "D8",
        picture: "Asura", 
    },
    "Archs": {
      raceDescription: "A race of Elephont like humanoids known for their strength and their oppressive heritage",
      racialBonus: "+2 to 1st Attack Roll",
      racialAbility: "Stomp - Can stoomp target for D12 damage",
      racialNegative: "-2 to 1st Dodge Roll",
      hpBonus: "+10",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D12",
        defenseProwess: "D4",
        picture: "Archs",
    },
    "Antaleer": {
      raceDescription: "A race of Deerlike humanoids known for their quick reflexes and their ability to blend in with their surroundings",
      racialBonus: "Reflex +3",
      racialAbility: "Rack Attack - Can use Antleers to gore target for D4 damage",
      racialNegative: "Intelligence -2",
      hpBonus: "+8",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D8",
        defenseProwess: "D8",
        picture: "Antaleer",
    },
    "Ikaw": {
      raceDescription: "A race of hawk-like humanoids known for their keen eyesight and their ability to fly",
      racialBonus: "Reflex +2",
      racialAbility: "Flight - Focus Ability",
      racialNegative: "Fortitude -1",
      hpBonus: "+7",
        startingJinx: "35",
        startingLevel: "4",
        attackProwess: "D8",
        defenseProwess: "D8",
        picture: "Ikaw",
    },
    "Gira": {
      raceDescription: "A race of Giraffe-like humanoids known for their twin bodies with the small intelligent head coming out of their backs with two small arms",
      racialBonus: "Reflex +2",
      racialAbility: "Top Shelf - Can re-roll any critical fails",
      racialNegative: "Fortitude -1",
      hpBonus: "+5",
        startingJinx: "40",
        startingLevel: "4",
        attackProwess: "D8",
        defenseProwess: "D8",
        picture: "Gira",
    },
    "Isegun": {
      raceDescription: "An aquatic race of humanoids known for their coral crowns and their matching skin color",
      racialBonus: "Fortitude +2",
      racialAbility: "Waterbreathing",
      racialNegative: "Strength -2",
      hpBonus: "+6",
        startingJinx: "40",
        startingLevel: "4",
        attackProwess: "D6",
        defenseProwess: "D10",
        picture: "Isegun",
    },
    "Glowhraun": {
      raceDescription: "A race of rhino like creatures who sacrifice their horns for their magical abilities, but have yeti like hair growing in patches all over their bodies",
      racialBonus: "Strength +2",
      racialAbility: "GlowOrb - a magical orb that can be used to cast minor torch light",
      racialNegative: "Reflex -1",
      hpBonus: "+7",
        startingJinx: "30",
        startingLevel: "2",
        attackProwess: "D12",
        defenseProwess: "D4",
        picture: "Glowhraun",
    },
    "Hwamps": {
      raceDescription: "A race of sentient swamp creatures known for their constant 'hwamping' sound",
      racialBonus: "Reflex +5",
      racialAbility: "Waterbreathing",
      racialNegative: "Charisma -5",
      hpBonus: "+3",
        startingJinx: "40",
        startingLevel: "6",
        attackProwess: "D6",
        defenseProwess: "D10",
        picture: "Hwamps",
    },
    "Giants": {
      raceDescription: "A race of giant humanoids known for their size and strength",
      racialBonus: "Strength +2",
      racialAbility: "Giants Elements - Can add their Elemental Racial hertiage to their Damage Types (fire, storm, ice, etc)",
      racialNegative: "Reflex -2",
      hpBonus: "+9",
        startingJinx: "30",
        startingLevel: "3",
        attackProwess: "D12",
        defenseProwess: "D4",
        picture: "Giants",
    },
    "Taurava": {
      raceDescription: "A race of minotaur-like humanoids known for their massive size and their resistance to fire",
      racialBonus: "-5 to All Fire Damage",
      racialAbility: "Rage - Can increase size by 1.5 ft and adds half current level to strength until end of encounter",
      racialNegative: "Intelligene -1",
      hpBonus: "+8",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D12",
        defenseProwess: "D6",
        picture: "Taurava",
    },
    "Warve": {
      raceDescription: "A race of aqautic based dwarvenkind known for their ability to swim and their resistance to cold",
      racialBonus: "Intelligence +2",
      racialAbility: "Waterblast - Focus Ability",
      racialNegative: "Fortitude -1",
      hpBonus: "+8",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D6",
      defenseProwess: "D10",
      picture: "Warve",
    },
    "Selvan": {
      raceDescription: "A race of Aquatic Elvkind known for their diplomacy and thier coral skin-features", 
      racialBonus: "Charisma +2",
      racialAbility: "Waterbreathing",
      racialNegative: "Strength -2",
      hpBonus: "+6",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Selvan",
    },
    "Namors": {
      raceDescription: "A race of aqautic humanoids known for their tentacles coming from their face and their mulitple eyes",
      racialBonus: "Strenght +2",
      racialAbility: "Waterbreathing",
      racialNegative: "Charisma -2",
      hpBonus: "+6",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Namors",
    },
    "Elvitch": {
      raceDescription: "A race of Elvkind known for their beauty and their ability to ride dire animals",
      racialBonus: "Reflex +2",
      racialAbility: "Tame Mount once per session",
      racialNegative: "Intelligence -2",
      hpBonus: "+7",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D8",
      defenseProwess: "D6",
      picture: "Elvitch", 
    },
    "Taotum": {
      raceDescription: "A race of humans who have evolved to have actual magic essence or Essos in their blood",
      racialBonus: "Intelligence +2",
      racialAbility: "Will of Essos - Can sub Intelligence for Strength for 1D4 rounds",
      racialNegative: "Charisma -1",
      hpBonus: "+8",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D4",
      picture: "Taotum",
    },
    "Vulturan": {
       raceDescription: "A race of eagle-like humanoids known for their keen eyesight and their ability to fly",
      racialBonus: "Strength +2",
      racialAbility: "Flight - Focus Ability",
      racialNegative: "Reflex -1",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D8",
      defenseProwess: "D6",
      picture: "Vulturan",
    },
    "Ryderz": {
      raceDescription: "A race of tiny humingbirdlike humanoids known for their small staure and their ability to ride small winged creatures",
      racialBonus: "+1 to Dodge Rolls",
      racialAbility: "Tame Mount once per session",
      racialNegative: "-1 to Attack Rolls",
      hpBonus: "+1",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D6",
      defenseProwess: "D12",
      picture: "Ryderz",
    },
    "Lightling": {
      raceDescription: "A race of half-Angel and half-Humans known for their search for knowledge and their chrome skin",
      racialBonus: "Intelligence +3",
      racialAbility: "Flight - Focus Ability",
      racialNegative: "Strength -3",
      hpBonus: "+6",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Lightling",
    },
    "Musculus": {
      raceDescription: "A race of mouse-like humanoids known for their logic and debating skills",
      racialBonus: "Reflex +2",
      racialAbility: "Vibe - Focus Ability",
      racialNegative: "Fortitude -2",
      hpBonus: "+3",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D6",
      defenseProwess: "D10",
      picture: "Musculus",
    },
    "Gemborne": {
      raceDescription: "A race of magical dwarvenkind known for thier crystal-like hair and their exclusive ability to cast gem magic",
      racialBonus: "Fortitude +2",
      racialAbility: "Gem Hardy - Adds Fortitude to all Magic Damage",
      racialNegative: "Strength -2",
      hpBonus: "+6",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D8",
      defenseProwess: "D10",
      picture: "Gemborne",
    },
    "Elves": {
      raceDescription: "A race of Elvkind known for their beauty and their unique ears",
      racialBonus: "Reflex +1",
      racialAbility: "Tree Walking - Can walk on trees and branches without Acrobatics checks",
      racialNegative: "Fortitude -1",
      hpBonus: "+6",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D6",
      defenseProwess: "D10",
      picture: "Elves",
    },
    "Larve": {
      raceDescription: "A volcanic race of dwarvenkind that have beards and hair made of ethereal flames",
      racialBonus: "Fortitude +2",
      racialAbility: "Combusition - Focus Ability",
      racialNegative: "Reflex -3",
      hpBonus: "+7",
      startingJinx: "30",
      startingLevel: "4",
      attackProwess: "D8",
      defenseProwess: "D10",
      picture: "Larve",
    },
    "Ruetree": {
      raceDescription: "A race of sentient trees whose origin and purpose is unknown",
      racialBonus: "Fortitude +2",
      racialAbility: "Tree Walking - Can walk on trees and branches without Acrobatics checks",
      racialNegative: "Reflex -2",
      hpBonus: "+10",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D6",
      defenseProwess: "D12",
      picture: "Ruetree",
    },
    "Eltic": {
      raceDescription: "A race of elvenkind known for their yeti like appearance and their ability to survive in the coldest of climates",
      racialBonus: "Strength +1",
      racialAbility: "Cold Hardy - All attacks add D4 Frost damage",
      racialNegative: "Fortitude -1",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Eltic",
    },
    "Viporian": {
      raceDescription: "A race of viper-like humanoids known for their colorful scales and their ability to survive off little water",
      racialBonus: "Reflex +4",
      racialAbility: "Slither Strike - Undodgable attack D4 once per encounter if they roll below 50% on percentiles they will be poisoned",
      racialNegative: "Fortitude -3",
      hpBonus: "+7",
      startingJinx: "30",
      startingLevel: "4",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Viporian",
    },
    "Crimrik": {
      raceDescription: "A race of humanoids whose powerful builds echo ancient reptiles",
      racialBonus: "Fortitude +1",
      racialAbility: "Tame Mount once per session",
      racialNegative: "Intelligence -1",
      hpBonus: "+5",
      startingJinx: "20",
      startingLevel: "2",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Crimrik",
    },
    "Mirrormen": {
      raceDescription: "A race of humanoids whose skin is made of a reflective material whose origins and purpose is unknown",
      racialBonus: "+2 to Attack Rolls",
      racialAbility: "Mirror Image - Can create a mirror image of themselves once per encounter",
      racialNegative: "-2 to Dodge Rolls",
      hpBonus: "+6",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D10",
      defenseProwess: "D10",
      picture: "Mirrormen",
    },
    "Froll": {
      raceDescription: "A race of volcanic trollkind known for their fiery tempers and their pension for throwing small flaming rocks at travelers",
      racialBonus: "Strength +2",
      racialAbility: "Enflame - Can enflame small projectiles with fire.  Causes standard damage for said projectile + 1 D4 fire damage",
      racialNegative: "Reflex -2",
      hpBonus: "+7",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D12",
      defenseProwess: "D6",
      picture: "Froll",
    },
    "Peaton": {
      raceDescription: "A race of peacock-like humanoids known for their colorful feathers and their telekinetic abilities",
      racialBonus: "Intelligence +2",
      racialAbility: "Telekensis - lbs x Level",
      racialNegative: "Strength -2",
      hpBonus: "+6",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D6",
      defenseProwess: "D6",
      picture: "Peaton",
    },
    "Roostins": {
      raceDescription: "A race of Rooster-like humanoids known for their short stature and annoying personalities",
      racialBonus: "Fortitude +2",
      racialAbility: "Rooster Call - Can call for help once per encounter",
      racialNegative: "Charisma -2",
      hpBonus: "+8",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "2 D4",
      defenseProwess: "D12 + D4",
      picture: "Roostins",
    },
    "Dragonaire": {
      raceDescription: "A race of dragon-like humanoids known for their ability to fly and their acid or smoke breath",
      racialBonus: "Fortitude +2",
      racialAbility: "Breath Weapon(Acid or Smoke)",
      racialNegative: "Strength -2",
      hpBonus: "+9",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Dragonaire",
    },

    "Dwarves": {
      raceDescription: "A race of dwarvenkind known for their strength and their ability to drink large amounts of alcohol",
      racialBonus: "Fortitude +3",
      racialAbility: "Shake it off - Can shake off any negative effects once per encounter",
      racialNegative: "Reflex -1",
      hpBonus: "+8",
      startingJinx: "35",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Dwarves",
    },
    "Humans": {
      raceDescription: "The most common and scattered race known for their adaptability and their ability to learn quickly",
      racialBonus: "Strength +2",
      racialAbility: "Additional weapon training",
      racialNegative: "Fortitude -1",
      hpBonus: "+8",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D6",
      defenseProwess: "D10",
      picture: "Humans",
    },
    "Contruct": {
      raceDescription: "A race of magicl constructs made of wood and metal whose purpose is dependant on their creator",
      racialBonus: "Fortitude +2",
      racialAbility: "Repair - Can repair themselves once per encounter",
      racialNegative: "Charisma -2",
      hpBonus: "+8",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D8",
      defenseProwess: "D10",
      picture: "Contruct",
    },
    "Panthari": {
      raceDescription: "A race of panther-like humanoids known for their agility and their ability to see in the dark",
      racialBonus: "Reflex +2",
      racialAbility: "Night Vision",
      racialNegative: "Charisma -2",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D10",
      defenseProwess: "D8",
      picture: "Panthari",
    },
    "Redhorn": {
      raceDescription: "A race of half-Demon half-Humans known for their genderswapped bodies-heads and red horns",
      racialBonus: "Fortitude +3",
      racialAbility: "Meltdown - Focus Ability",
      racialNegative: "Charisma -2",
      hpBonus: "+7",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D8",
      picture: "Redhorn",
    },
    "Minotaur": {
      raceDescription: "A race of minotaurs known for their strength and their years of enslavement",
      racialBonus: "Strength +3",
      racialAbility: "Bull Rush - Can rush a target and knock them prone once per encounter",
      racialNegative: "Intelligence -1",
      hpBonus: "+8",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D12",
      defenseProwess: "D6",
      picture: "Minotaur",
    },
    "Laotu": {
      raceDescription: "A race of snail like humanoids born from chaotic magic",
      racialBonus: "Fortitude +2",
      racialAbility: "Shell - Can use their shell to block all critical hits",
      racialNegative: "Strength -2",
      hpBonus: "+9",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D12",
      defenseProwess: "D10",
      picture: "Laotu",
    },
    "Turtan": {
      raceDescription: "A race of turtle-like humanoids known for their hard shells and their ability to swim",
      racialBonus: "Fortitude +3",
      racialAbility: "Rocksteady - Able to add Fort Stat to Luck based Rolls",
      racialNegative: "Charisma -2",
      hpBonus: "+10",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D6",
      defenseProwess: "D12",
      picture: "Turtan",
    },
    "Djinni": {
      raceDescription: "A race of humanoids with varying hues of blue or violet known for their ability to grant wishes",
      racialBonus: "Charisma +2",
      racialAbility: "Wish - Can grant a wish once per session at a terrible cost",
      racialNegative: "Fortitude -2",
      hpBonus: "+6",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Djinni",
    },
    "Foxum": {
      raceDescription: "A race of fox-like humanoids known for their cunning and their hunting skills",
      racialBonus: "Fortitude +1",
      racialAbility: "First strike - Unfocused Ability",
      racialNegative: "Strength -1",
      hpBonus: "+8",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D8",
      defenseProwess: "D10",
      picture: "Foxum",
    },
    "Havgin": {
      raceDescription: "A race of half-Djinni half-Elv known for their skin of varying hues of green, blue, orange, or violet",
      racialBonus: "Intelligence +3",
      racialAbility: "Restful Lamp - Can rest inside a Lamp for a full rest in 1 hour",
      racialNegative: "Strength -2",
      hpBonus: "+7",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Havgin",
    },
    "Ramiel": {
      raceDescription: "A race of ramlike humanoids known for their horns and their dangerous headbutt ability",
      racialBonus: "Strength +1",
      racialAbility: "Headbutt - Can headbutt a target for D12 damage",
      racialNegative: "Charisma -2",
      hpBonus: "+7",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D8",
      defenseProwess: "D10",
      picture: "Ramiel",
    },
    "Centorc": {
      raceDescription: "A race of centaur-orc creatures with four arms the bottom half of a horse and the top half of an orc.",
      racialBonus: "Strength +2",
      racialAbility: "Double Take - Focus Ability",
      racialNegative: "Fortitude -4",
      hpBonus: "+7",
      startingJinx: "25",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Centorc",
    },
    "Tunkles": {
      raceDescription: "A sentient race of magical steam-powered constructs known for their ability to replicate their origin unknown",
      racialBonus: "Intelligence +5",
      racialAbility: "Replicate - Able to build other tunkles.  They will not automatically obey you.",
      racialNegative: "Minus 2 to all other stats except Charisma",
      hpBonus: "+1",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D8", 
      defenseProwess: "D4",
      picture: "Tunkles",
    },
    "Denbark": {
       raceDescription: "A race of dog-like humanoids known for their loyalty and their ability to see in the dark",
      racialBonus: "Strength +2",
      racialAbility: "Night Vision",
      racialNegative: "Charisma -1",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Denbark",
    },
    "Owlec": {
      raceDescription: "A race of owl-like humanoids known for their wisdom and their ability to aerial hunt",
      racialBonus: "Reflex +3",
      racialAbility: "Flight - Focus Ability",
      racialNegative: "Strength -2",
      hpBonus: "+4",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D6",
      defenseProwess: "D10",
      picture: "Owlec",
    },
    "Jedanako": {
      raceDescription: "A race of elvenkind that evolved in the Magical Forest of Ever to have a cyclopian and laser eye",
      racialBonus: "Reflex +2",
      racialAbility: "Cyclopian Eye - Beams of light shoot from left your eye doing D12 damage",
      racialNegative: "Charisma -2",
      hpBonus: "+7",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Jedanako",  
    },
    "Torro": {
      raceDescription: "A race of alligator like humanoids known for their strength and their angry outbursts",
      racialBonus: "Strength +2",
      racialAbility: "Surge - Unfocused Ability",
      racialNegative: "Charisma -3",
      hpBonus: "+9",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D10",
      defenseProwess: "D10",
      picture: "Torro",
    },
    "Gorak": {
      raceDescription: "A race of Gorilla like humanoids known for their strength and their secluded nature",
      racialBonus: "Strength +3",
      racialAbility: "Gorak's Charm - Can sub any Charisma stat with their Strength Stat",
      racialNegative: "Charisma -1",
      hpBonus: "+7",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D12",
      defenseProwess: "D6",
      picture: "Gorak",
    },
    "Caneis": {
      raceDescription: "A race of coyote-like humanoids known for their cunning and their tribalistic customs and rituals",
      racialBonus: "Strength +2",
      racialAbility: "Coyote Call - Can call for help once per encounter",
      racialNegative: "Fortitude -1",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D8",
      defenseProwess: "D6",
      picture: "Caneis",
    },
    "Spelorian": {
      raceDescription: "A race of bald humanoids known for their ability to transulcent purple and pink chest and letters floating around their heads in a forgotten language",
      racialBonus: "Intelligence +2",
      racialAbility: "Telepathy",
      racialNegative: "Charisma -2",
      hpBonus: "+6",
      startingJinx: "20",
      startingLevel: "3",
      attackProwess: "D8",
      defenseProwess: "D6",
      picture: "Spelorian",
    },
    "Troll": {
      raceDescription: "A race of troll-like humanoids known for their strength and huge noses",
      racialBonus: "Strength +2",
      racialAbility: "Riddle - Can ask a riddle off any target that is currently on a bridge.  If they are unable to answer it then you receive 1 D20 Gold",
      racialNegative: "-1 to Dodge Rolls",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Troll",
    },
    "Q": {
      raceDescription: "A race of magical Squirrels known for their bravery and their quick reflexes",
      racialBonus: "Intelligence +3",
      racialAbility: "Swift - Two Actions Per Turn",
      racialNegative: "Strength -3",
      hpBonus: "0",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D4",
      defenseProwess: "D12",
      picture: "Q",
    },
    "Soulless": {
      raceDescription: "A race of sentient Statues known for their mischievous nature and their ability to replicate themselves",
      racialBonus: "Intelligence +5",
      racialAbility: "Replicate - Can replicate themselves once per encounter",
      racialNegative: "Charisma -4",
      hpBonus: "+5",
      startingJinx: "20",
      startingLevel: "3",
      attackProwess: "D12",
      defenseProwess: "D12",
      picture: "Soulless",
    },
    "Zarut": {
      raceDescription: "A race snakelike humanoids covered with white fur and long tails coming from the back of their head",
      racialBonus: "Strength +2",
      racialAbility: "Tail Whip - Can whip a target with their tail for D6 damage",
      racialNegative: "Reflex -1",
      hpBonus: "+8",
      startingJinx: "30",
      startingLevel: "4",
      attackProwess: "D12",
      defenseProwess: "D6",
      picture: "Zarut",
    },
    "Otorc": {
      raceDescription: "A race of hulking orckind known for their colossal size and strength and just as much stupidity",
      racialBonus: "Strength +3",
      racialAbility: "Rage - Can increase size by 1.5 ft and adds half current level to strength until end of encounter",
      racialNegative: "-2 to Dodge Rolls",
      hpBonus: "+9",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D12",
      defenseProwess: "D4",
      picture: "Otorc",
    },

    "Brinx": {
      raceDescription: "A race of 1ft tall winged fairy-like humanoids known for their ability to fly and their magic heritage",
      racialBonus: "Charisma +1",
      racialAbility: "Flight - Focus Ability",
      racialNegative: "Strength -2",
      hpBonus: "+3",
      startingJinx: "40",
      startingLevel: "4",
      attackProwess: "D4",
      defenseProwess: "D12+2",
      picture: "Brinx",
    },

    "Toric": {
      raceDescription: "A race of magical minotaurkind known for their ability to cast magic and strong but slender builds",
      racialBonus: "Intelligence +1",
      racialAbility: "Warmage - Replace any Fortitude checks with Intelligence",
      racialNegative: "Fortitude -2",
      hpBonus: "+8",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D8",
      defenseProwess: "D10",
      picture: "Toric",
    },

    "Duogoblin": {
      raceDescription: "A race of two-headed goblinkind known for their cunning and their ability to speak any language once heard",
      racialBonus: "+1 to Attack Rolls",
      racialAbility: "Dual Speak - Can speak any language once heard",
      racialNegative: "Intelligence -2",
      hpBonus: "+8",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D12",
      defenseProwess: "D6",
      picture: "Duogoblin",
    },

    "Melanni": {
      raceDescription: "An aquatic race of elvenkind known for their beauty and the coral that grows from the side of their head",
      racialBonus: "Intelligence +2",
      racialAbility: "Waterbreathing",
      racialNegative: "Strength -2",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Melanni",
    },
    
    "Gonjic": {
      raceDescription: "A fur covered race of magically connected beings known for their ability sense and discern magic",
      racialBonus: "Fortitude +2",
      racialAbility: "Sense and Discern Magic",
      racialNegative: "Charisma -1",
      hpBonus: "+6",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D8",
      defenseProwess: "D8",
      picture: "Gonjic",
    },

    "Jaddehb": {
      raceDescription: "A djinn based raced.  If the Djinni got all the good attributes of Jin the First then the Jaddehb took one his worst attributes and made it their own",
      racialBonus: "Reflex +2",
      racialAbility: "Restful Lamp - Can rest inside a Lamp for a full rest in 1 hour",
      racialNegative: "Strength -2",
      hpBonus: "+8",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Jaddehb",
    },

    "Polkans": {
      raceDescription: "A race of centaurs with head of horse on top of the body as well.  They were magically reborn from the fallen centaurs of the past",
      racialBonus: "Strength +1",
      racialAbility: "Double Take - Focus Ability",
      racialNegative: "Reflex -3",
      hpBonus: "+8",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Polkans",
    },

    "Skorc": {
      raceDescription: "A race of half-Orc and half-human known for their hardiness and their refusal to eat sentient flesh",
      racialBonus: "Fortitude +2",
      racialAbility: "Orc Strength - +3 to Stength Checks",
      racialNegative: "Charisma -2",
      hpBonus: "+7",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D8",
      picture: "Skorc",
    },

    "Delvian": {
      raceDescription: "A race of elvenkind with lunar abilities and quick reflexes",
      racialBonus: "Reflex +2",
      racialAbility: "Moonlit - Gains a temporary plus 5 to HP when in Moonlight",
      racialNegative: "Charisma -1",
      hpBonus: "+6",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D8",
      defenseProwess: "D10",
      picture: "Delvian",
    },

    "Tib": {
      raceDescription: "A race of tiny humanoids with cherub like faces known for their stealth and their sleight of hand abilities",
      racialBonus: "Charisma +5",
      racialAbility: "Pickpocket - Plus 5 to all Sleight of Hand checks",
      racialNegative: "Strength -2",
      hpBonus: "+3",
      startingJinx: "40",
      startingLevel: "5",
      attackProwess: "D6",
      defenseProwess: "D10",
      picture: "Tib",
    },

    "Orc": {
      raceDescription: "A race of orcish humanoids known for their strength and their ability to cannibilistic tendencies",
      racialBonus: "Strength +2",
      racialAbility: "Brute Resolve - Can add Strength to any Fortitude check",
      racialNegative: "Intelligence -1",
      hpBonus: "+7",
      startingJinx: "35",
      startingLevel: "4",
      attackProwess: "D12",
      defenseProwess: "D8",
      picture: "Orc",
    },

    "Jackal": {
      raceDescription: "A race of rabbit like humanoids known for their speed and their ability to jump great distances",
      racialBonus: "Strength +1",
      racialAbility: "Double Take - Focus Ability",
      racialNegative: "Reflex -2",
      hpBonus: "+7",
      startingJinx: "25",
      startingLevel: "2",
      attackProwess: "D6",
      defenseProwess: "D8",
      picture: "Jackal",
    },

    "Drowland": {
      raceDescription: "A race of reptilian weasel hybrids known for their cunning and their fire or frost breath attacks",
      racialBonus: "Reflex +1",
      racialAbility: "Breath Weapon (Fire or Frost)",
      racialNegative: "Strength -1",
      hpBonus: "+9",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D8",
      picture: "Drowland",
    },

    "Manticlus": {
      raceDescription: "A race of insect like humanoids with 4 arms that are known for their mysterious society and their secretive nature",
      racialBonus: "Fortitude +2",
      racialAbility: "Double Down - Unfocused Ability",
      racialNegative: "Charisma -2",
      hpBonus: "+9",
      startingJinx: "30",
      startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D6",
      picture: "Manticlus",
    },

    // Add data for other races
  };
  

export default raceData;

//       'Manticlus',
//       'Octubian',
//       'Dawsp',
//       'Boon',
//       'Trinon',
//       'Shifter',
//       'Thyst',
//       'Wereman',
//       'Ivotien',
//       'Mannenite',
//       'Dragon',
//       'Oakrels',
//       'Felynx',
//       'Treeton',
//       'Goblin',
//       'Blood Elf',
//       'Cuth',
//       'Magelv',
//       'Bisanu',
//       'Potec',
//       'Banda',
//       'Cabat',
//       'Cossakus',