const raceData = {
    "Badgurix": {
      raceDescription: "A badger like race of strong warriors",
      racialBonus: "Strength +1",
      racialAbility: "Shield Proficiency",
      racialNegative: "Intelligence =1",
      hpBonus: "+10",
      startingJinx: "30",
        startingLevel: "3",
      attackProwess: "D10",
      defenseProwess: "D8",
      picture: "Badgurix",
    },
    "Telecliss": {
      raceDescription: "A plant like race of humanoids known for their kinship with nature ",
      racialBonus: "Reflex +5",
      racialAbility: "Telepathy",
      racialNegative: "Cannot Speak any spoken language",
      hpBonus: "+9",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D6",
        defenseProwess: "D10",
    },
    "Augtens": {
        raceDescription: "A race of aquatic humanoids known for the symbiotic relationship with intelliegent squids",
        racialBonus: "Intelligence +2",
        racialAbility: "Water Breathing",
        racialNegative: "Fortitude -2",
        hpBonus: "+7",
        startingJinx: "25",
        startingLevel: "2",
        attackProwess: "D10",
        defenseProwess: "D6",
    },
    "Cabat": {
        raceDescription: "A race of Gremlin batlike hybrids known for their cunning and trickery",
        racialBonus: "Dexterity +2",
        racialAbility: "Flight",
        racialNegative: "Strength -2",
        hpBonus: "+5",
        startingJinx: "20",
        startingLevel: "1",
        attackProwess: "D8",
        defenseProwess: "D8",
        picture: "Cabat",
    }
    // Add data for other races
  };
  

export default raceData;

// 'Badgurix',
//       'Augtens',
//       'Asura',
//       'Archs',
//       'Antaleer',
//       'Ikaw',
//       'Gira',
//       'Isegun',
//       'Glowhraun',
//       'Telecliss',
//       'Hwamps',
//       'Giants',
//       'Taurava',
//       'Warve',
//       'Selvan',
//       'Namors',
//       'Elvitch',
//       'Taotum',
//       'Vulturan',
//       'Ryderz',
//       'Lightling',
//       'Musculus',
//       'Gemborne',
//       'Elves',
//       'Larve',
//       'Ruetree',
//       'Eltic',
//       'Viporian',
//       'Crimrik',
//       'Mirrormen',
//       'Froll',
//       'Peaton',
//       'Roostins',
//       'Dragonaire',
//       'Dwarves',
//       'Humans',
//       'Contruct',
//       'Panthari',
//       'Redhorn',
//       'Minotaur',
//       'Laotu',
//       'Turtan',
//       'Djinni',
//       'Foxum',
//       'Havgin',
//       'Ramiel',
//       'Centorc',
//       'Tunkles',
//       'Denbark',
//       'Owlec',
//       'Jedanako',
//       'Torro',
//       'Gorak',
//       'Caneis',
//       'Spelorian',
//       'Troll',
//       'Q',
//       'Soulless',
//       'Demon',
//       'Zarut',
//       'Otorc',
//       'Brinx',
//       'Toric',
//       'Duogoblin',
//       'Melanni',
//       'Gonjic',
//       'Jaddehb',
//       'Polkans',
//       'Zadnaut',
//       'Skorc',
//       'Delvian',
//       'Tib',
//       'Orc',
//       'Jackal',
//       'Drowland',
//       'Manticlus',
//       'Octubian',
//       'Dawsp',
//       'Boon',
//       'Trinon',
//       'Shifter',
//       'Thyst',
//       'Wereman',
//       'Ivotien',
//       'Mannenite',
//       'Dragon',
//       'Oakrels',
//       'Felynx',
//       'Treeton',
//       'Goblin',
//       'Blood Elf',
//       'Cuth',
//       'Magelv',
//       'Bisanu',
//       'Potec',
//       'Banda',
//       'Cabat',
//       'Cossakus',