const raceMapping = {
    Badgurix: 'Badgurix',
    Telecliss: 'Telecliss',
    Hwamps: 'Hwamps',
    Giants: 'Giants',
    Taurava: 'Taurava',
    Warve: 'Warve',
    Selvan: 'Selvan',
    Namors: 'Namors',
    Elvitch: 'Elvitch Spirit Rider',
    Taotum: 'Taotum',
    Vulturan: 'Vulturan',
    Ryderz: 'Ryderz',
    Lightling: 'Lightling',
    Musculus: 'Musculus',
    Gemborne: 'Gemborne',
    Elves: 'Elves',
    Larve: 'Larve',
    Ruetree: 'Ruetree',
    Eltic: 'Eltic',
    Viporian: 'Viporian',
    Crimrik: 'Crimrik',
    Mirrormen: 'Mirrormen',
    Froll: 'Froll',
    Peaton: 'Peaton',
    Roostins: 'Roostins',
    Dragonaire: 'Dragonaire',
    Dwarves: 'Dwarves',
    Humans: 'Humans',
    Contruct: 'Contruct',
    Panthari: 'Panthari',
    Redhorn: 'Redhorn',
    Minotaur: 'Minotaur',
    Laotu: 'Laotu',
    Turtan: 'Turtan',
    Djinni: 'Djinni',
    Foxum: 'Foxum',
    Augtens: 'Augtens',
    Asura: 'Asura',
    Archs: 'Archs',
    Antaleer: 'Antaleer',
    Ikaw: 'Ikaw',
    Gira: 'Gira',
    Isegun: 'Isegun',
    Glowhraun: 'Glowhraun',
  };

  export default raceMapping;